/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface ROILead {
  'id' : bigint,
  'name' : string,
  'hourlyWage' : number,
  'email' : string,
  'timestamp' : bigint,
  'staffHours' : number,
  'phone' : string,
  'monthlyRevenue' : number,
  'totalMonthlyGain' : number,
  'lostLeads' : number,
  'avgOrderValue' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdmin' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteContactSubmission' : ActorMethod<[bigint], boolean>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactSubmissionById' : ActorMethod<[bigint], [] | [ContactSubmission]>,
  'getContacts' : ActorMethod<[], Array<ContactSubmission>>,
  'getROILeads' : ActorMethod<[], Array<ROILead>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'becomeFirstAdmin' : ActorMethod<[], boolean>,
  'hasAdminBeenAssigned' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContact' : ActorMethod<[string, string, string], bigint>,
  'submitROILead' : ActorMethod<
    [string, string, string, number, number, number, number, number, number],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];